winget install --id GitHub.GitHubDesktop -e --source winget
winget install --id Microsoft.VisualStudioCode.Insiders -e --source winget
winget install --id Microsoft.VisualStudioCode -e --source winget
winget install --id Microsoft.PowerShell -e --source winget
winget install --id Microsoft.WindowsTerminal -e --source winget
winget install --id CoreyButler.NVMforWindows -e --source winget
winget install --id pnpm.pnpm -e --source winget
winget install --id Neovim.Neovim -e --source winget
winget install --id Microsoft.VisualStudio.2022.Community -e --source winget
winget install --id Notion.Notion -e --source winget
winget install --id Google.AndroidStudio -e --source winget
winget install --id dbeaver.dbeaver -e --source winget
winget install --id Docker.DockerDesktop -e --source winget
winget install --id Microsoft.PCManager -e --source winget
winget install --id Microsoft.Edge -e --source winget
winget install --id Microsoft.DevHome -e --source winget
winget install --id MongoDB.Compass.Full -e --source winget
winget install --id OBSProject.OBSStudio -e --source winget
winget install --id Microsoft.OneDrive -e --source winget
winget install --id Rustlang.Rustup -e --source winget
winget install --id Valve.Steam -e --source winget
winget install --id Microsoft.VisualStudio.2022.BuildTools -e --source winget
winget install --id Insomnia.Insomnia -e --source winget
winget install --id Python.Python.3.11 -e --source winget
winget install --id GlavSoft.TightVNC -e --source winget
winget install --id Python.Launcher -e --source winget
winget install --id Microsoft.PowerToys -e --source winget
winget install --id AnyDeskSoftwareGmbH.AnyDesk -e --source winget
winget install --id Microsoft.VCRedist.2015+.x86 -e --source winget
winget install --id Mobatek.MobaXterm -e --source winget
winget install --id Logitech.OptionsPlus -e --source winget
winget install --id Microsoft.VCRedist.2015+.x64 -e --source winget
winget install --id RonyShapiro.PasswordSafe -e --source winget
winget install --id Microsoft.XNARedist -e --source winget
winget install --id Microsoft.WindowsSDK.10.0.22000 -e --source winget
winget install --id GoLang.Go -e --source winget
winget install --id Discord.Discord -e --source winget
winget install --id GIMP.GIMP -e --source winget
winget install --id rjpcomputing.luaforwindows -e --source winget
winget install --id Highresolution.X-MouseButtonControl -e --source winget
winget install --id zig.zig -e --source winget
winget install --id Oracle.JavaRuntimeEnvironment -e --source winget
winget install --id Telegram.TelegramDesktop -e --source winget
winget install --id Twilio.Authy -e --source winget
# Esto existe por si falla el import de winget