import './globals.css'
import LayoutCss from "@/app/StylesModules/layout.module.css";
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<main className={LayoutCss.layout}>
					{children}
				</main>
			</body>
		</html>
	)
}
